### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by cyberdooof** [RedKatz/SocialMediaHackingToolkit#20]
File "/home/cyber@@@@/Desktop/SocialMediaHackingToolkit/smh.py", line 389, in <module>
    Lines = file1.readlines() 
            ^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 923: invalid continuation byte

**Comment by RedKatz** [comment]
can you provide more info? what did you do for encounting this error

**Comment by zm-ibrahim** [comment]
i have similar problem .

Traceback (most recent call last):
  File "/home/user/SocialMediaHackingToolkit/smh.py", line 254, in <module>
    InstagramBruteforce()
  File "/home/user/SocialMediaHackingToolkit/smh.py", line 76, in InstagramBruteforce
    Lines = file1.readlines()
            ^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 932: invalid continuation byte

this happened when i give wordlist to the bruteforce section

**Comment by RedKatz** [comment]
what is the amount of word contained in the wordlist?

**Comment by zm-ibrahim** [comment]
i don't know. but the file size is 133 MB

**Comment by RedKatz** [comment]
fixed in new version, 0.3.2, please report any type of error, ty for contribute
