### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by somethingidktaken** [RedKatz/SocialMediaHackingToolkit#57]
I got this error when I was trying to bruteforce a twitter account using rockyou.txt
I had VPN turned off aswell
What should i do to fix it?
I was running kali linux
Thanks for any help i get!

Traceback (most recent call last):
  File "/home/kali/SocialMediaHackingToolkit/cmd/main.py", line 59, in <module>
    twitter_bruteforce(username, wordlist, vpn)
  File "/home/kali/SocialMediaHackingToolkit/cmd/utils.py", line 468, in twitter_bruteforce
    wl_lines = [line.strip() for line in wl_file.readlines()]  # Rimuovi i caratteri di nuova riga
                                         ^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 933: invalid continuation byte

**Comment by RedKatz** [comment]
change wordlist this contains undecoded characters
