### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by Saadafian** [RedKatz/SocialMediaHackingToolkit#90]
Not working Facebook brute Force, after inputing username, it shows; 

:: username ::

                                                       [choice] > saadafian
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/SocialMediaHackingToolkit/cmd/main.py", line 35, in <module>
    username = get_facebook()()                                      ^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable

**Comment by sheykandi** [comment]
Same here:
Traceback (most recent call last):
  File "C:\Users\50769\Downloads\SocialMediaHackingToolkit-0.3.2\SocialMediaHackingToolkit-0.3.2\cmd\main.py", line 36, in <module>
    username = get_facebook()()
               ^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
My system:
Windows 11
python-3.12.0b4-amd64

**Comment by sheykandi** [comment]
Removing the last paretheses `()` from the _**main.py**_ file, _line 36_, did the trick.
Change this:
`username = get_facebook()()`
to this:
`username = get_facebook()`
At least it lets me continue to the next step, the wordlist.
